### ISSUE TITLE
[META] Create main page components

### ISSUE THREAD

**Issue by SolomiiaLomnytska22** [SolomiiaLomnytska22/AI-Chat-React#3]
This issue is focused on creating the main page for the chat:
- [x] Create custom input component (https://github.com/SolomiiaLomnytska22/AI-Chat-React/issues/4)
- [x] Create messages area (https://github.com/SolomiiaLomnytska22/AI-Chat-React/issues/5)
- [x] Create side menu (https://github.com/SolomiiaLomnytska22/AI-Chat-React/issues/10)
